const actionConstants = {
  SUMMONER_DATA_SUCCESS: "SUMMONER_DATA_SUCCESS",
  SUMMONER_DATA_FAILURE: "SUMMONER_DATA_FAILURE",
  TEXT_INPUT_CHANGE: "TEXT_INPUT_CHANGE",
  IMAGE_LOADED: "IMAGE_LOADED",
  FETCH_STATIC_SUCCESS: 'FETCH_STATIC_SUCCESS',
}

export default actionConstants;
