const actionConstants = {
  SUMMONER_DATA_SUCCESS: 'SUMMONER_DATA_SUCCESS',
  SUMMONER_DATA_FAILURE: 'SUMMONER_DATA_FAILURE',
  TEXT_INPUT_CHANGE: 'TEXT_INPUT_CHANGE',
  IMAGE_LOADED: 'IMAGE_LOADED',
  FETCH_STATIC_SUCCESS: 'FETCH_STATIC_SUCCESS',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  SET_MATCH_DETAILS: 'SET_MATCH_DETAILS',
  CLEAR_SUMMONER_DATA: 'CLEAR_SUMMONER_DATA',
  FETCHING_DATA: 'FETCHING_DATA',
}

export default actionConstants;
